config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :results, only: %i[index] do
    collection { post 'show_result', to: 'results#show_result', as: :show }
    collection { get 'verify_result', to: 'results#verify_result', as: :verify }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/results_controller.rb
# frozen_string_literal: true

# app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :check_params, only: :show_result

  def index; end

  def show_result
    set_parsed_result

    if @parsed_result[:error]
      flash[:error] = @parsed_result[:message]
      redirect_to results_path
    end

    # Storing in session
    session[:parsed_result] = @parsed_result
  end

  def verify_result
    @parsed_result = session[:parsed_result]
    # Clearing the data in session
    session.delete(:parsed_result)

    @recruitbot_api_resp = RecruitbotApi.new(@parsed_result).call

  rescue SocketError => e
    flash[:error] = e.message
    redirect_to results_path
  end

  private

  def result_params
    params.permit(
      :name,
      :email,
      :upload,
      :text,
      :url
    )
  end

  def check_params
    raise CustomException::CompulsoryParamMissing unless compulsory_param_available?

    check_data_param_validity
    url_valid if result_params[:url].present?
  rescue CustomException::CompulsoryParamMissing, CustomException::DataParamMissing, CustomException::OnlyOneDataParamAllowed,
         CustomException::NotPersonalityUrl => e
    flash[:error] = e.message
    redirect_to results_path
  end

  def url_valid
    raise CustomException::NotPersonalityUrl unless result_params[:url].match(%r{https://www.personalitytest.net/cgi-bin/shortipipneo3.cgi}).present?
  end

  def check_data_param_validity
    raise CustomException::DataParamMissing unless data_param_available?

    raise CustomException::OnlyOneDataParamAllowed if multiple_data_param?
  end

  def compulsory_param_available?
    (result_params[:name].present? && result_params[:email].present?)
  end

  def data_param_available?
    (result_params[:upload].present? || result_params[:text].present? || result_params[:url].present?)
  end

  def multiple_data_param?
    count = 0
    count += 1 if result_params[:upload].present?
    count += 1 if result_params[:text].present?
    count += 1 if result_params[:url].present?

    count > 1
  end

  def set_parsed_result
    @parsed_result = PersonalityTestResultParser.new(
      result_params[:name],
      result_params[:email],
      {
        file: result_params[:upload],
        text: result_params[:text],
        url: result_params[:url]
      }
    ).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalityResultParser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
  </head>

  <body>
    <div class="bg-light">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid justify-content-center">
          <a class="navbar-brand" href="<%= results_path %>">Personality Test</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </nav>

      <%= yield %>
    </div>
  </body>
</html>

app/views/results/_show_parsed_data.html.erb
<h2>
    <%= title %>
</h2>
<div class="container mt-4 py-3">
    <div class="row">
        <div class="col-3">
            &nbsp;
        </div>
        <div class="col-6">
            <pre class="wrap-text"><%= JSON.pretty_generate(data) %></pre>
        </div>
        <div class="col-3">
            &nbsp;
        </div>
    </div>
</div>

app/views/results/index.html.erb
<%= javascript_pack_tag 'results' %>

<% flash.each do |type, msg| %>
  <% alert_name = {'error': 'danger', 'success': 'success', 'notice': 'info'}.with_indifferent_access %>

  <div class="text-center alert alert-<%= alert_name[type]%>">
    <%= msg %>
  </div>
<% end %>

<%= bootstrap_form_with(url: show_results_path, local: true) do |f| %>
  <div class="form-content-wrapper pt-3 mt-3">
    <%= f.text_field :name, required: true %>
    <%= f.email_field :email, required: true %>
    <div class="alert alert-info mt-3" role="alert">
      You can only use one of the following!!!
    </div>
    <%= f.file_field :upload, id: 'file', accept: "text/plain, text/html" %>
    <%= f.text_area :text, id: 'text' %>
    <%= f.url_field :url, id: 'url' %>
    <%= f.submit "Submit", class: "btn btn-secondary mt-3" %>
  </div>
<% end %>

app/views/results/show_result.html.erb
<%= render partial: "show_parsed_data", locals: { title: 'The result parsed from the provided data is shown below:', data: @parsed_result } %>

<%= button_to "Verify from RecruitBot API", { action: "verify_result" }, method: :get, class: "btn btn-secondary mt-3 ml-5" %>

app/views/results/verify_result.html.erb
<%= render partial: "show_parsed_data", locals: { title: 'The result obtained from RecruitBot API is shown below:', data: @recruitbot_api_resp } %>

<%= button_to "Homepage", { action: "index" }, method: :get, class: "btn btn-secondary mt-3 ml-5" %>